// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserSeviceClient is the client API for UserSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSeviceClient interface {
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type userSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSeviceClient(cc grpc.ClientConnInterface) UserSeviceClient {
	return &userSeviceClient{cc}
}

func (c *userSeviceClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserSevice/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSeviceServer is the server API for UserSevice service.
// All implementations must embed UnimplementedUserSeviceServer
// for forward compatibility
type UserSeviceServer interface {
	AddUser(context.Context, *User) (*User, error)
	mustEmbedUnimplementedUserSeviceServer()
}

// UnimplementedUserSeviceServer must be embedded to have forward compatible implementations.
type UnimplementedUserSeviceServer struct {
}

func (UnimplementedUserSeviceServer) AddUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserSeviceServer) mustEmbedUnimplementedUserSeviceServer() {}

// UnsafeUserSeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSeviceServer will
// result in compilation errors.
type UnsafeUserSeviceServer interface {
	mustEmbedUnimplementedUserSeviceServer()
}

func RegisterUserSeviceServer(s grpc.ServiceRegistrar, srv UserSeviceServer) {
	s.RegisterService(&UserSevice_ServiceDesc, srv)
}

func _UserSevice_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSeviceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSevice/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSeviceServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSevice_ServiceDesc is the grpc.ServiceDesc for UserSevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserSevice",
	HandlerType: (*UserSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserSevice_AddUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
